language: python
python:
 - '3.8'

install:
 - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="application.settings.travis"

services:
 - postgresql

script:
 - cd projet/ && python manage.py test -v3
