language: python
python:
 - '3.8'

install:
 - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="hydropo.travis_settings"

services:
 - postgresql


script:
  - cd projet/ && python manage.py test
#- python projet/manage.py test
