language: python
python:
 - '3.8'

install:
 - pip install -r requirements.txt

services:
 - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U 

script:
  - cd projet/ && python manage.py test
#- python projet/manage.py test
