language: python
python:
 - '3.8'

install:
 - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="hydropo.settings.travis"

services:
 - postgresql

script:
 - python projet/manage.py test -v3
