# Generated by Django 3.1 on 2020-08-24 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rpi",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="WaterSchedule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("begin", models.TimeField()),
                ("end", models.TimeField()),
                (
                    "rpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rpi_manager.rpi",
                    ),
                ),
            ],
        ),
    ]
