# Generated by Django 3.1 on 2020-12-10 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("rpi_manager", "0002_ph"),
    ]

    operations = [
        migrations.CreateModel(
            name="LightSchedule",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("begin", models.TimeField()),
                ("end", models.TimeField()),
                (
                    "rpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rpi_manager.rpi",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ec",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                ("value", models.IntegerField()),
                (
                    "rpi",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rpi_manager.rpi",
                    ),
                ),
            ],
        ),
    ]
