# Generated by Django 3.1 on 2020-12-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rpi_manager", "0003_ec_lightschedule"),
    ]

    operations = [
        migrations.AddField(
            model_name="ec",
            name="objectif",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ph",
            name="objectif",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
