# Generated by Django 3.1 on 2021-06-16 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpi_manager', '0008_auto_20210427_1751'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rpi',
            old_name='md5_name',
            new_name='uid_name',
        ),
    ]
